# 第一种配置方式，路由映射规则配置在gateway的application.yml配置文件
#server:
#  port: 10001
#spring:
#  application:
#    name: gateway-demo
#  cloud:
#    gateway:
#      routes:
#        - id: security-demo # 路由的编号，唯一ID
#          uri: https://www.oschina.net # 路由到的地址
#          predicates: # 断言，路由匹配的规则
#            - Path=/oschina
#          filters: # 过滤器，对请求进行拦截，实现自定义的功能，对应 FilterDefinition 数组
#            #  在请求的过程中去掉请求匹配的前缀，比如在这里如果访问 http:localhost:10001/oschina ,那么就会匹配到 https://www.oschina.net
#            - StripPrefix=1
#      discovery:
#        locator:
#          enabled: true # 开启和 spring cloud 注册中心的集成，默认为false
#          url-expression: "'lb://' + serviceId" # 路由的目标地址的表达式
#    nacos:
#      discovery:
#        server-addr: 192.168.127.152:8848 # 配置 nacos 注册中心地址

# 第二种方式，由 nacos 动态管理路由映射规则，映射信息保存在 bootstrap.yaml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.127.152:8848
